### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by lukasp2** [gugoan/economizzer#106]
Hi,

which configurations are needed to ru economizzer via nginx reverse proxy ?

Thank you & BR,
Lukas

**Comment by gugoan** [comment]
Hello my friend.
I've never used NGINX, but the requirements are the same to run any app with Yii Framework 2.

Take a look here: [http://www.yiiframework.com/forum/index.php/topic/55108-how-to-configure-yii2-website-with-nginx-location/](http://www.yiiframework.com/forum/index.php/topic/55108-how-to-configure-yii2-website-with-nginx-location/)
