### ISSUE TITLE
Dockerfile for easy deployment

### ISSUE THREAD

**Issue by skhoroshavin** [gugoan/economizzer#112]
Would be great :)

**Comment by gugoan** [comment]
Sorry but I plan to keep this project small and minimalistic

**Comment by skhoroshavin** [comment]
Well, having dockerfile doesn't mean project is no longer minimalistic - in fact it's just reference to some base image and some commands to install and run application. The problem (at least for me) is that anyone not familiar with PHP development and related tools might just fail to deploy your app (to be honest, I failed - stuck with composer failing to install some packages for no obvious reason).
