### ISSUE TITLE
yii migrate error: Failed opening required '/root/economizzer/vendor/autoload.php

### ISSUE THREAD

**Issue by bilalashraf03** [gugoan/economizzer#113]
Hey gugoan,

I have followed the instructions for installing economizzer,
- clonned the repo
- edit config.php file with my db settings
- execute "./yii migrate" but it gives me error: 

```
PHP Warning:  require(/root/economizzer/vendor/autoload.php): failed to open stream: No such file or directory in /root/economizzer/yii on line 17
PHP Fatal error:  require(): Failed opening required '/root/economizzer/vendor/autoload.php' (include_path='.:/usr/share/php') in /root/economizzer/yii on line 17
```

Please give me your feedback, i really appreciate it. Thanks

**Comment by gugoan** [comment]
Hello,
Migrations are in trouble and I could not fix them. 
Install the database through the SQL file itself at the project's root: `economizzer.sql`
