### ISSUE TITLE
How configure email

### ISSUE THREAD

**Issue by SilvioMessi** [gugoan/economizzer#114]
Hi,
I have installed Economizzer on my own server, but the emails are not sent. How can I configure the email settings?
Thank you,
Silvio

**Comment by gugoan** [comment]
Hello,
You need to follow the mailer setup instructions for the Yii2 Framework itself.

A basic configuration that works for me is (depends on your server too):

```
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'messageConfig' => [
                'from' => ['noreply@yourmailprovider.com' => 'Support'],
                'charset' => 'UTF-8',
            ]
        ],
```
