### ISSUE TITLE
Running from command line without Apache/Nginx

### ISSUE THREAD

**Issue by sundarv85** [gugoan/economizzer#115]
Hello

I'm trying to use economizzer for personal use and instead of running apache or nginx, would it possible to start economizzer from command line and then use it. And once done, just stop that.

Thanks

**Comment by gugoan** [comment]
Hello,
No, it needs a web server, you can even try the web server embedded in PHP7 (for example), but the project was built using APACHE specifications (mod_rewrite, etc).
