### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by sjmiaklee** [gugoan/economizzer#119]
Is there an admin panel/view that can create/manage accounts?
Also, I want to create an external login page OR use the user database I have to login. Is that possible?
Thanks!

**Comment by gugoan** [comment]
Hello,
No, the system has no account creation / management feature.

Yes, you can use another login database, but you will need to change the authentication mechanism used.

**Comment by sjmiaklee** [comment]
Can you please point out which page/file(s) contain login mechanism? I went through the files but cannot quite figure it out. Thanks!

**Comment by gugoan** [comment]
It at:
models/User.php
I use this ext: https://github.com/amnah/yii2-user
