### ISSUE TITLE
web/user/login

### ISSUE THREAD

**Issue by F3rr3ir4** [gugoan/economizzer#120]
Good afternoon.
I installed it in the www / html / economizzer folder but when it accesses it it redirects me to / economizzer / web / user / login but it says it does not exist on the server, how to redirect it?

**Comment by gugoan** [comment]
Hi,
Try set the `EnablePrettyUrl = false.`
[https://yii2-cookbook.readthedocs.io/enable-pretty-urls/](https://yii2-cookbook.readthedocs.io/enable-pretty-urls/)

Or ..
Can be any configuration of your Apache. The REWRITE_MOD is enabled?

**Comment by gugoan** [comment]
No return
