### ISSUE TITLE
Cant get this to work.

### ISSUE THREAD

**Issue by eyden92** [gugoan/economizzer#122]
Hello.
Iv'e been trying to set up Economizzer on a droplet on digital ocean, i tried with LAMP 16.04, one click install so it should have all dependencies.
Also installed php-xml, php-mbstring and php-curl.

When trying the `composer global require "fxp/composer-asset-plugin:^1.3.1"` i get 2 errors about some script somewhere but dosnt seem like it fais.

Then i try the `composer install`, and when its done. I try to go to the website but only get 500 website error. Tried to CHMOD 777 the whole directory, that didnt work either.

Please help, thank you in advance.

**Comment by gugoan** [comment]
Hi,
Try set the EnablePrettyUrl = false.
[https://yii2-cookbook.readthedocs.io/enable-pretty-urls/](https://yii2-cookbook.readthedocs.io/enable-pretty-urls/)

Or ..
Can be any configuration of your Apache. The REWRITE_MOD is enabled?
