### ISSUE TITLE
date

### ISSUE THREAD

**Issue by germanoalves** [gugoan/economizzer#125]
oi tudo bem?

Como eu consigo ajustar o formato da data do campo de pesquisa para dd-mm-yyyy?

obg e parabens pelo projeto!

**Comment by gugoan** [comment]
Olá, blz?
Obrigado :D

No componente `kartik\widgets\DatePicker`, tem o parametro `format` pra vc setar o formato desejado.
A ideia é que o valor não seja digitado e sim, selecionado. Como o sistema utiliza a funcionalidade de internacionalização, fica dificil verificar o formato da data de cada idioma e converter para o formato do banco de dados.

Mas no seu caso, vc pode usar apenas o formato **pt-br** e então fazer a conversão antes de gravar no BD.

**Comment by germanoalves** [comment]
o caminho seria vendor\kartik-v\yii2-widgets  ? Eu não encontrei a pasta "kartik", somente com esse '-v'. É isso mesmo?

**Comment by gugoan** [comment]
@germanoalves 
Voce pode alterar isso em cada instancia (abaixo) do componente ou de modo global. Ou ainda mudar o idioma da aplicação apos se autenticar.

```
    <?php
        echo DatePicker::widget([
            'model' => $model,
            'form' => $form,
            'attribute' => 'date',
            'type' => DatePicker::TYPE_INPUT,
            'size' => 'sm',
            'pluginOptions' => [
                'autoclose'=>true,
                'todayHighlight' => true,
                'format' => 'yyyy-mm-dd',
            ]
        ]);
    ?>
```
