### ISSUE TITLE
data cadastro

### ISSUE THREAD

**Issue by germanoalves** [gugoan/economizzer#126]
Ola tudo bem?
Gostaria de formatar a data do cadastro de contas. Já tentei editar os arquivos _form.php e CashbookController.php, mas sempre quando tento editar a data para "dd-mm-yyyy" na listagem de lançamentos fica assim "dd-mm-0001". Como posso realizar esse formatação?

Grato!

**Comment by gugoan** [comment]
Quando voce muda o idioma para portugues, o componente datepicker automaticamente fica em portugues. Porem se vc deseja digitar a data numero por numero, tem que usar o formato do banco de dados.

Não implementei isso no sistema por que ele é multi-idioma.
