### ISSUE TITLE
Error adding extension

### ISSUE THREAD

**Issue by fcasanellas** [gugoan/economizzer#128]
Hi!

I'm trying to create a feature to import cashbook items in CSV in format. I would like to use the yii2-import extension (https://github.com/lucasguo/yii2-import) but adding it with
 
`composer require lucasguo/yii2-import "*"`

I obtain the following error

`[UnexpectedValueException] Could not parse version constraint &&: Invalid version string "&&" `

Any idea?

**Comment by gugoan** [comment]
I do not know about this extension friend!
The import feature will be added in the future.
