### ISSUE TITLE
mysql issue 

### ISSUE THREAD

**Issue by hrbudding** [gugoan/economizzer#129]
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))
MySQL said: Documentation

#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation

**Comment by salmankhatrii** [comment]
I run query of SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
But still same error is showing. Working on localhost

**Comment by gugoan** [comment]
fix de sql problems
