### ISSUE TITLE
error to create entries

### ISSUE THREAD

**Issue by nguyen-h** [gugoan/economizzer#131]
Hey, thx for sharing your great tool, but after installing I get the following error 

"Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: kartik\widgets\DatePicker::_container" 

when I select entries and want to add some ...

Update: I installed your tool on MAMP ... localhost on my macbook.

**Comment by gugoan** [comment]
Hi, 
fix the kartik datepicker
