### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by rdleiria** [gugoan/economizzer#133]
Hello,

I am having an error when creating a new entry with an image to upload. I attached screenshots here.

I tried to increase upload sizes in php.ini, but no success.

Any help, please?

Regards
![1](https://user-images.githubusercontent.com/20798560/42596741-1e02b4f2-852d-11e8-8464-fe9ec657aaea.png)
![2](https://user-images.githubusercontent.com/20798560/42596742-1e29fd28-852d-11e8-94ee-ccca153fc24c.png)
![3](https://user-images.githubusercontent.com/20798560/42596743-1e4ff96a-852d-11e8-928a-f89686697331.png)

**Comment by rdleiria** [comment]
Hi,

Thanks for your reply.

Yes, I did the following in php.ini.

> file_uploads = On
> upload_max_filesize = 50M
> post_max_size = 50M
> max_file_uploads = 20

After that I restarted Apache, but I got the same error.

**Comment by gugoan** [comment]
Hello,
@rdleiria 
Without attach file you can insert registry normally?

I'll try to reproduce the error

**Comment by rdleiria** [comment]
Hello @gugoan,

Yes, I can. Please, take a look in the attached screenshots.

![1](https://user-images.githubusercontent.com/20798560/42704603-df7ada0e-86a6-11e8-9a72-bf03d731f613.png)
![2](https://user-images.githubusercontent.com/20798560/42704604-dfa193e2-86a6-11e8-9d16-0078163a0dc0.png)

**Comment by rdleiria** [comment]
Hello everybody,

Thanks for your previous replies.

Any news about error? I am moving from my Windows app to control finances to Economizzer.
If you think that this error is too much complicated to fix, I can try another web software.

Regards{}

**Comment by gugoan** [comment]
Hi,
I believe it is easy to solve, I will do a fresh installation on different virtual machines, tonight.

**Comment by MrBRB** [comment]
Hi
I had trouble to change upload size from 2Mb, too. I solved it with creating a "user.ini" with content _post_max_size = 90M
upload_max_filesize = 50M_
in path "/etc/php/7.0/apache2/conf.d" 

Only with this custome file added the upload size changed and I had no more issues. Seems that Apache2 doesn't work with changes in "/etc/php/7.0/apache2/php.ini " any more.

**Comment by rdleiria** [comment]
Hi @MrBRB,

Thanks for your reply.

I gave-up from this system. I developed a new one to my own use.

Thanks anyway.
