### ISSUE TITLE
Live Demo: Getting 'Incorrect password' when trying to logon with 'joe' & '123456'

### ISSUE THREAD

**Issue by pommetjehorlepiep** [gugoan/economizzer#135]
Tried to logon to the demo as per details described [here](https://github.com/gugoan/economizzer).
Getting 'Incorrect password'.

**Comment by gugoan** [comment]
Hi,
Fixed.
You can try again?

**Comment by pommetjehorlepiep** [comment]
Yes, it's fixed. Thx
