### ISSUE TITLE
No date picker when creating new balance entries

### ISSUE THREAD

**Issue by MrBRB** [gugoan/economizzer#136]
Hi,
I'm facing a problem I can't solve with multiple times reinstallation. When trying to create a new entry the date picker doesn't show up. I have installed apache2, php7, mysql, phpmyadmin, composer (globally) and followed your instructions. Have I missed a depencey/package? Unfortunately I am not a pro user, still learning ervery minute. Please help me to understand what is missing. At the moment its not so cool to add older entries as I have to manipulate them all afterwards in phpmyadmin.

Thanks,
Regards
MrBRB

![grafik](https://user-images.githubusercontent.com/43027620/45215944-48756f00-b29f-11e8-9fd7-123fe9e4e95e.png)

**Comment by MrBRB** [comment]
I have attached a php-info pdf. I hope this helps to find out what is missing in my installation.
Thanks!

[PHP_INFO.pdf](https://github.com/gugoan/economizzer/files/2384483/PHP_INFO.pdf)

**Comment by MrBRB** [comment]
I have attached a php-info pdf. I hope this helps to find out what is missing in my installation.
Thanks!

[PHP_INFO.pdf](https://github.com/gugoan/economizzer/files/2384483/PHP_INFO.pdf)

**Comment by gugoan** [comment]
There was an error in the code :(

**Comment by MrBRB** [comment]
OK, within the composer part? Can I fix this without reinstall?

**Comment by MrBRB** [comment]
Ah I saw it. Thanks its working now!
