### ISSUE TITLE
currency symbol

### ISSUE THREAD

**Issue by radamanthysdev** [gugoan/economizzer#14]
Change the currency symbol by locale selected (EN, PT)

**Comment by samdark** [comment]
http://gostash.it/en/stashes/327

**Comment by gugoan** [comment]
Hi @samdark 
It is a bad practice to use the currency symbol in the message file?

**Comment by samdark** [comment]
Nope. It's OK.

**Comment by gugoan** [comment]
hi @radamanthysdev ,
For now, we will continue using currency symbols on their mail files, I believe it simpler.
