### ISSUE TITLE
Floating

### ISSUE THREAD

**Issue by nodefive** [gugoan/economizzer#155]
It is possible to display two floating numbers for the integers? So, display 500.00 instead of 500.
![image](https://github.com/gugoan/economizzer/assets/49776670/d95baa7a-2e39-4e1f-be1f-fa6829d3276f)

**Comment by nodefive** [comment]
Solved changing _views/cashbook/index.php_

From:
`return $model->is_pending === 0 ? '<strong style="color:'.$model->type->hexcolor_type.'">'.' '.$model->value.'</strong>' :
`
To:
`return $model->is_pending === 0 ? '<strong style="color:'.$model->type->hexcolor_type.'">'.' '.number_format((float)$model->value, 2, '.', '').'</strong>' :`

**Comment by gugoan** [comment]
I chose to implement the `Yii::$app->formatter->asDecimal($model->value)` formatter to maintain the internationalization functionality
