### ISSUE TITLE
Categories and sub-categories

### ISSUE THREAD

**Issue by gugoan** [gugoan/economizzer#21]
Categories chance to Categories with sub-categories

**Comment by ooii** [comment]
Hi, is this coming at short-term?
Thanks.

**Comment by gugoan** [comment]
Hi,
Yes, will soon be in production.
My prediction is this December

**Comment by ooii** [comment]
Good. Thanks. I'd like to test economizzer and eventually start a fresh year with.

**Comment by ooii** [comment]
Hi, I know that december is still long (3 weeks) but any clue on that?
Thanks.

**Comment by gugoan** [comment]
@ooii 
Hello,
I believe that in the next COMMIT this month is ready and in production. I am also in need of this feature.
This week I'm involved in another project.

**Comment by ooii** [comment]
Thanks.

**Comment by gugoan** [comment]
Added functionality
@ooii

**Comment by ooii** [comment]
Thanks. I was right now trying to install it. I'm facing some issues, I open tickets.
