### ISSUE TITLE
Fix language pt and auto detect

### ISSUE THREAD

**Issue by gugoan** [gugoan/economizzer#25]
Add cat
Portuges

**Comment by phprocks** [comment]
Hi,
Try this http://www.ip2location.com/developers/yii

http://www.yiiframework.com/extension/yii2-ip2location/
http://www.ip2location.com/

**Comment by gugoan** [comment]
nice! 
Thanks, but first i will try "Detecting language automatically" 
https://github.com/samdark/yii2-cookbook/blob/master/book/i18n-selecting-application-language.md

Or this post
http://stackoverflow.com/questions/3770513/detect-browser-language-in-php
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference
