### ISSUE TITLE
Add Social Auth

### ISSUE THREAD

**Issue by radamanthysdev** [gugoan/economizzer#28]
Why not implement a authentication by Social networks feature ?

**Comment by samdark** [comment]
Implementation could be looked up in https://github.com/samdark/yiifeed. It's no ideal there but could be a good start.

**Comment by ercling** [comment]
I intend to do this task.

**Comment by gugoan** [comment]
Good
I'm thinking of using the very functionality of Yii2-user extension amnah. What do you think? @ercling 

https://github.com/amnah/yii2-user/blob/master/SOCIAL.md

**Comment by ercling** [comment]
@gugoan I agree.

**Comment by gugoan** [comment]
okay then
If it works properly, it sends a PULL REQUEST

**Comment by radamanthysdev** [comment]
is possible merge an existing account with an account created by social network?

**Comment by samdark** [comment]
In my case — yes.

**Comment by gugoan** [comment]
@ercling , authentication through Facebook or Google+ fine with you?
How to set up your url on Facebook and Google+?

**In Google+ is appearing:**
 400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request: http://www.economizzer.org/economizzer/web/index.php?r=user%2Fauth%2Flogin&amp;authclient=google did not match a registered redirect URI.

**In Facebook is appearing:**
The URL entered is not permitted by the application configuration: One or more of the provided URLs are not allowed in the application settings. The URL must match the URL of the website or URL Canvas, or domain should be a subdomain of one of the application domains

**Comment by ercling** [comment]
Hello @gugoan 

There is a bug in GoogleOAuth client. 
I fixed it by overriding getReturnUrl() method:
```php
class GoogleOAuth extends BaseGoogleOAuth{
    private $_returnUrl;

    /**
     * Fix double encoded redirect_uri
     *
     * @return string
     */
    public function getReturnUrl()
    {
        if ($this->_returnUrl === null) {
            $this->_returnUrl = $this->defaultReturnUrl();
        }
        return urldecode($this->_returnUrl);
    }
}
```

I am prepearing a pull request to economizzer with Google+, Facebook, Twitter and Vkontakte authentification. It will be ready later today.

**Comment by gugoan** [comment]
@ercling , after the PR Social auth # 37, when I try to authenticate by google+ keeps popping up error. See how this configuration in my console.developers.google.com.

(tested on localhost and production)

![95skjt0](https://cloud.githubusercontent.com/assets/1585443/10431957/9116ea78-70de-11e5-88ef-aa2211418d77.jpg)

take a look: http://www.economizzer.org/economizzer/web/index.php?r=user%2Flogin

**Comment by ercling** [comment]
Authorized redirect URIs must contains two URIs: one fore login, another for connect. Try to add this and let me know:
http://www.economizzer.org/economizzer/web/index.php?r=user/auth/login&authclient=google

**Comment by gugoan** [comment]
Nice!!!! 
work fine :)

i will try with facebook now

**Comment by ercling** [comment]
I forgot to add social auth widget to user/register page. I will fix it tomorrow

**Comment by gugoan** [comment]
okay
in facebook auth work fine too

**Comment by gugoan** [comment]
Authentication via social network implemented
