### ISSUE TITLE
File uploaded don't work on Update and Delete 

### ISSUE THREAD

**Issue by phprocks** [gugoan/economizzer#3]
Make the file upload works on Update and Delete actions

Based on: 
http://webtips.krajee.com/advanced-upload-using-yii2-fileinput-widget/
http://webtips.krajee.com/upload-file-yii-2-using-fileinput-widget/

**Comment by gugoan** [comment]
Fix it! :dart: 
By follow: http://webtips.krajee.com/advanced-upload-using-yii2-fileinput-widget/
