### ISSUE TITLE
Add accounts for incomes and expenses

### ISSUE THREAD

**Issue by ercling** [gugoan/economizzer#39]

**Comment by gugoan** [comment]
You mean the categories?
(categories of expenditure and revenue categories)

**Comment by ercling** [comment]
@gugoan No. I mean accounts like bank accounts ("My VISA", "Wallet", "Deposit" e.t.c.) I need this functionality and I'm going to do it.

**Comment by gugoan** [comment]
Ok, I get it.
Good functionality to include in the **Economizzer**.
Some other financial management systems I tested also have multiple accounts.

**Comment by gugoan** [comment]
implemented authentication
Finished in PR # 40

**Comment by ooii** [comment]
I cannot find this feature. How do you add an account?

**Comment by gugoan** [comment]
This functionality has been removed for now.
Impacted in major changes in the system, and ended up leaving a bit of focus

**Comment by MPATTS** [comment]
@ercling How is that working out for yah?
Plan to share your code?
