### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by muhahacz** [gugoan/economizzer#44]
Hi, thanks for a first good looking selfhosted opensource money management software :)

I guess there is a long way to fully develop this software, but i have several alternatives...
..i hope you find some inspiration in this software (moneyflow, tricky money management, moneymanager - basically clones), because it looks like direct competitor to economizzer
Demo URL: http://demo.ibilling.io/moneyflow/ 
Username: admin 
Password: 123456 

On the other hand, if you aim high, there is buxfer ( https://demo.buxfer.com/dashboard ) which is very sophisticated software.

Thanks
keep it up :)

**Comment by gugoan** [comment]
Hello, thanks for the comments.
You mentioned great tools! Sure are good references for us to improve Economizzer. I am filing this material and will perform some more detailed tests on these systems.

But at first, the idea of Economizzer is simplicity and keep as a Free and Opensource solution. Here in Brazil tested several good tools, but always had some legal recourse that was paid, it motivated me to develop Economizzer (and also to develop the skills to PHP and Yii Framework).

A big hug :)
