### ISSUE TITLE
(Still) Cannot not run it

### ISSUE THREAD

**Issue by ooii** [gugoan/economizzer#47]
Hello Gustavo,

I'm still not able to run economizzer. I updated my repository and ran `composer` again. First, I got the following issue during the installation: 
```
Problem 1
    - Can only install one of: amnah/yii2-user[3.0.0, dev-master].
    - Can only install one of: amnah/yii2-user[dev-master, 3.0.0].
    - Can only install one of: amnah/yii2-user[3.0.0, dev-master].
    - Installation request for amnah/yii2-user 3.0.0 -> satisfiable by amnah/yii2-user[3.0.0].
    - Installation request for amnah/yii2-user == 9999999-dev -> satisfiable by amnah/yii2-user[dev-master].
```
I removed `amnah/yii2-user` and ran `composer` again without any issue.
Now, when trying to access the web page I have:
```
ReflectionException

Class amnah\yii2\user\components\User does not exist
```
More details are available here: http://pastebin.com/7vjNvw2G
Tested on OSX and synology with same behavior.

**Comment by ooii** [comment]
Tried to run it on a fresh ubuntu, I got the same error:
```
Problem 1
    - Can only install one of: amnah/yii2-user[dev-master, 3.0.0].
    - Can only install one of: amnah/yii2-user[3.0.0, dev-master].
    - Installation request for amnah/yii2-user ^3.0 -> satisfiable by amnah/yii2-user[3.0.0].
    - Installation request for amnah/yii2-user == 9999999-dev -> satisfiable by amnah/yii2-user[dev-master].
```

**Comment by gugoan** [comment]
@ooii 
Sorry, you are actually giving error. Try running:
~~~
composer update
~~~
I did here and worked on Ubuntu and Win7

**Comment by ooii** [comment]
I can't understand. It does not work here. Still this error after `composer update` and `composer require "fxp/composer-asset-plugin:~1.0"`. Still the same issue.
Can it come from the database? Because `mysqlimport -u root -pmypassword --local economizzer economizzer.sql` gives `mysqlimport: Error: 1146, Table 'economizzer.economizzer' doesn't exist, when using table: economizzer`

**Comment by gugoan** [comment]
That's weird.
1. Try to import the file economizar.sql by phpmyadmin
2. Let me see your file composer.json

**Comment by gugoan** [comment]
@ooii 
You could install?

**Comment by ooii** [comment]
Gustavo, I'm out for vacation since yesterday 2pm (right after my last message) with no access to my server. I'll try this afternoon with my iPad if I can ssh to it. At least, I hope I can send you the composer.json. 
Otherwise, I'll send it Saturday when I'm back home. Thanks.

**Comment by ooii** [comment]
Here is the composer.json:
ˋ`ˋ

{
    "name": "gugoan/economizzer",
    "description": "Open Source Personal Finance Manager",
    "keywords": ["yii2", "php", "finance", "money"],
    "homepage": "http://www.economizzer.org/",
    "type": "project",
    "license": "MIT",
    "authors": [
        {
            "name": "Gustavo G. Andrade",
            "email": "gugoan@hotmail.com",
            "homepage": "http://www.gustavoandrade.net.br",
            "role": "Developer"
        }    
    ],
    "support": {
        "issues": "https://github.com/gugoan/economizzer/issues",
        "source": "https://github.com/gugoan/economizzer"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-jui": "*",
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "miloschuman/yii2-highcharts-widget": "dev-master",
        "kartik-v/yii2-widgets": "*",
        "fxp/composer-asset-plugin": "~1.0"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },    
    "autoload": {
        "psr-0": {
            "Economizzer": "src"
        }
    },
     "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
ˋ`ˋ

**Comment by ooii** [comment]
So, I'm back from vacation to make some tests.
Imported the sql file with phpmyadmin, it did not fix the issue.
I figured out that `amnah/yii2-user` is not in `composer.son` so I added it. No, i think I go a little bit further. I have the following error: `Getting unknown property: amnah\yii2\user\models\forms\LoginForm::username`.
One question: is it normal that error messages use `\` instead of `/`?

**Comment by gugoan** [comment]
ok, I'm glad it worked

**Comment by ooii** [comment]
Me too, finally :)
