### ISSUE TITLE
[Request] Overview by (sub-)category

### ISSUE THREAD

**Issue by ooii** [gugoan/economizzer#49]
Personally, I only need such a tool to know where I spend my money either than knowing if I have more revenue than expense. Thus, I'd like to have the chart with expense per category. Are you planning to add it?
Thanks again.

**Comment by gugoan** [comment]
Yes, the area overview will be reformulated with more information and details of current month.

**Comment by gugoan** [comment]
Hi,
Included charts in **Overview > Monthly Summary** area.
Separated by category and segment

**Comment by ooii** [comment]
Thanks.
