### ISSUE TITLE
new install fails to load login page

### ISSUE THREAD

**Issue by ebayer** [gugoan/economizzer#50]
Fresh install on ubuntu trusty as root under apache leads to 404 on login page, apache access logs contains the following, while economizzer/runtime/logs/ is empty:

"GET /economizzer/web/user/login HTTP/1.1" 404 518 "http://46.101.209.38/economizzer/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"

What can I do to debug further?

**Comment by gugoan** [comment]
hi,
I can not reproduce this error. Try this in www directory:

```
sudo chmod - R 777 economizzer
sudo composer global require "fxp/composer-asset-plugin:~1.1.1"
cd economizzer
composer update
```

post your `composer.json` file

**Comment by gugoan** [comment]
Another attempt to find the problem: Remove the `HTACCESS` file and disable `enablePrettyUrl` in _config/web.php_.

and let me know here. :D

**Comment by ebayer** [comment]
The first set of commands did no change. I also realized I have not enabled the rewrite module, but enabling the module did not change anything.

removing htaccess and changing enablePrettyUrl solved the problem, I see the login screen and runtime/logs/app.log contains the following:

2016-02-29 21:12:10 [$IP1][-][-][warning][yii\debug\Module::checkAccess] Access to debugger is denied due to IP address restriction. The requesting IP address is $IP1
    in /var/www/html/economizzer/views/layouts/main.php:107
    in /var/www/html/economizzer/vendor/amnah/yii2-user/controllers/DefaultController.php:83
2016-02-29 21:12:10 [$IP1][-][-][info][application] $_GET = [
    'r' => 'user/login'
]

$_COOKIE = [
    'PHPSESSID' => 'j11dq8l0j9lcn2eo6u0bjmsq77'
    'csrftoken' => 'I198YzYOOOObdzsg3kf7pGxIw2VSSPKr'
    'sessionid' => 'yrgenw4og01g1w9rusb9cnj1bs109j0s'
]

$_SESSION = [
    '__flash' => []
    '__returnUrl' => '/economizzer/web/'
]

$_SERVER = [
    'HTTP_HOST' => '$IP2'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,tr;q=0.6'
    'HTTP_COOKIE' => 'PHPSESSID=j11dq8l0j9lcn2eo6u0bjmsq77; csrftoken=I198YzYOOOObdzsg3kf7pGxIw2VSSPKr; sessionid=yrgenw4og01g1w9rusb9cnj1bs109j0s'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at $IP2 Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)'
    'SERVER_NAME' => '$IP2'
    'SERVER_ADDR' => '$IP2'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '$IP1'
    'DOCUMENT_ROOT' => '/var/www/html'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/html'
    'SERVER_ADMIN' => 'webmaster@localhost'
    'SCRIPT_FILENAME' => '/var/www/html/economizzer/web/index.php'
    'REMOTE_PORT' => '48509'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'r=user%2Flogin'
    'REQUEST_URI' => '/economizzer/web/index.php?r=user%2Flogin'
    'SCRIPT_NAME' => '/economizzer/web/index.php'
    'PHP_SELF' => '/economizzer/web/index.php'
    'REQUEST_TIME_FLOAT' => 1456780330.442
    'REQUEST_TIME' => 1456780330
]

Enabling enablePrettyUrl back to true causes the problem for me. Removing the .htaccess file does not make any difference on its own.

**Comment by gugoan** [comment]
Fix
try: 
```
git clone https://github.com/gugoan/economizzer.git
cd economizzer
composer global require "fxp/composer-asset-plugin:~1.1.1"
composer install
```
