### ISSUE TITLE
Multiple Categories

### ISSUE THREAD

**Issue by sundarv85** [gugoan/economizzer#52]
Hello,

Would it be possible to allow multiple category selection. For e.g. I would like to see 

- How much I spent overall on Clothes
- How much was spent on Clothes for my Wife, for my children, and for me 

This would be very valuable to see where the money goes. Is such a thing possible?

**Comment by gugoan** [comment]
Is a good idea.
I thought something like TAGS for example.
Included for analysis in the TODO list.
