### ISSUE TITLE
Translate into korean

### ISSUE THREAD

**Issue by napiera** [gugoan/economizzer#53]
Hello.

I'm korean IT engineer and I want to use economizzer more easily.

As possible, do I translate this into korean?

**Comment by gugoan** [comment]
Hello,

Yes, if it can be translated.
Please find attached the compressed file containing the two files with the strings to be translated.

Or you can get in the path: `messages/ko/app.php` and `messages/ko/user.php`

[ko.zip](https://github.com/gugoan/economizzer/files/235539/ko.zip)

**Comment by gugoan** [comment]
Added.
thanks @napiera
