### ISSUE TITLE
Unable to make selection from drop down in new entry.

### ISSUE THREAD

**Issue by muramasatheninja** [gugoan/economizzer#64]
When creating a new entry. I'm unable to select a category from the drop down. The drop down appears but I'm unable to make any selections. I've tried in both Chrome and Firefox with the same results. I also tested the drop down while create category the "Parent Category" drop down works normally.

Thanks

**Comment by muramasatheninja** [comment]
You are right! Once I did this I was able to make my selection. Thanks for the help I'm sure I will be posting more later. :)

**Comment by gugoan** [comment]
:D
