### ISSUE TITLE
Please move up cashbook model at mobile view(on mobile devices)

### ISSUE THREAD

**Issue by PRIHLOP** [gugoan/economizzer#65]
In mobile view will be more comfortable if cashbook will be on the top of the page instead the filter. As variant you can make a function for saving condition of the collapsed filter.

Thanks.

**Comment by gugoan** [comment]
Yes, there was thought that too.
I'll try the filter area appear minimized by default.

**Comment by PRIHLOP** [comment]
I am find solution. But it work in desktop view to.
In this [file](https://github.com/gugoan/economizzer/blob/master/views/cashbook/index.php)  change string 21
`<div id="collapseFilter" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">`
Change to the following
`<div id="collapseFilter" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">`

This will be OK?
