### ISSUE TITLE
Class 'yii\authclient\clients\GoogleOAuth' not found

### ISSUE THREAD

**Issue by dfiel** [gugoan/economizzer#77]
After installing Economizzer on a new Ubuntu server, with nginx as a web server, browsing to the site gives the following error:
![image](https://cloud.githubusercontent.com/assets/7292540/17706182/05d354ec-63a9-11e6-8c39-cfce7f970802.png)

My nginx config is:
```text
server {
    listen 80;
    listen [::]:80;
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;

        }

    root /var/www/html/economizzer/web;

    client_max_body_size 300M;
    index index.php index.html index.htm;

    server_name econ.mydomain.com;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        autoindex on;
        sendfile off;
    }

}
```

**Comment by dfiel** [comment]
I don't need OAuth, this install will be only used by me and my girlfriend

**Comment by gugoan** [comment]
revised! :D
added `"yiisoft/yii2-authclient": "2.0.6"` in **composer.json** file
Run the `composer update` command and try again
