### ISSUE TITLE
Deleting Category: Method Not Allowed

### ISSUE THREAD

**Issue by dfiel** [gugoan/economizzer#79]
Clicking the trash can icon on the categories page (/category/index) results in a Method Not Allowed (#405) error.
![image](https://cloud.githubusercontent.com/assets/7292540/17839742/9be87aa6-67bf-11e6-8607-7c62cf9e4194.png)

**Comment by dfiel** [comment]
Deleting from the Category description page (category/10XX) works as expected.

**Comment by gugoan** [comment]
Thank you for showing the error!
Just fix the repository, but the online version will be sent in the next update to production this month.
