### ISSUE TITLE
Dashboard: Incorrect term

### ISSUE THREAD

**Issue by dfiel** [gugoan/economizzer#80]
On the dashboard, the bottom right graph is titled "Expenses by Segment". The title should instead be "Transactions by Segment". Or, exclude Revenue type transactions.

![image](https://cloud.githubusercontent.com/assets/7292540/17839866/c15f25c4-67c3-11e6-8279-37f74e328a13.png)

Obviously the large blue bar, a Deposit, was not an expense.

**Comment by phprocks** [comment]
@dfiel In this chart it appears only the records marked EXPENSE.
Check that records where selected "Deposit" are "as Expense".
![expense](https://cloud.githubusercontent.com/assets/1650192/17863072/8cf4419c-686e-11e6-8596-542a57f66214.jpg)

**Comment by phprocks** [comment]
@gugoan I checked here and realized that the graphics are not organized by the current month. It is showing consolidated. :-1:

**Comment by dfiel** [comment]
@phprocks Nope, the Deposits are marked as Revenue. My account balance is also correct

**Comment by gugoan** [comment]
@phprocks and @dfiel both of you are right!
- Fixed chart period (just current month / year).
- Fixed graphic name ("Transactions by Segment" really makes sense, considering I could not even get only the expenses).
