### ISSUE TITLE
Targets - Blank Page?

### ISSUE THREAD

**Issue by dfiel** [gugoan/economizzer#83]
Is targets an unimplemented feature, or is my installation borked? Targets seem perfect for me

**Comment by gugoan** [comment]
hello, is planned for the next version update. First I'm focused on fixing some minor bugs.

It will be a good feature to be implemented.

**Comment by dfiel** [comment]
Alright, sounds good!

**Comment by dfiel** [comment]
I'd recommend putting a Work in Progress header on the top of the page, because navigating to a blank page makes it seem like your installation is broken

**Comment by sbunciak** [comment]
Hi @gugoan , any estimate on when the Targets feature might be available? Thanks!
