### ISSUE TITLE
Can't select category when adding new expense

### ISSUE THREAD

**Issue by makaroni4** [gugoan/economizzer#84]
I've added 2 categories, but when I hover in form/select with keyboard – nothing happens.

Account: g1147200@mvrht.com

![screen shot 2016-08-24 at 8 59 02 am](https://cloud.githubusercontent.com/assets/768070/17921207/18e7161e-69d9-11e6-84cd-bdb947457f62.png)

**Comment by gugoan** [comment]
Hello, you enter parent category and then category?

**Comment by dfiel** [comment]
Yeah, as of now you need to put those categories under a parent category, such as Beverages in your example.

It takes a bit of getting used to, but it works pretty well.

**Comment by gugoan** [comment]
@makaroni4 
Let us know if it worked

**Comment by makaroni4** [comment]
@gugoan it worked, but I'd never figure out on my own)
