### ISSUE TITLE
No carry-over balance to next month in Dashboard Overview

### ISSUE THREAD

**Issue by PRIHLOP** [gugoan/economizzer#88]
First screenshot without carry-over balance to next month
![economizzer_screenshot1](https://cloud.githubusercontent.com/assets/16081788/18204116/a83bc886-7123-11e6-9946-4e3763510938.PNG)

Second screenshot with carry-over balance to next month (this changes in pull request #86 )
![economizzer_screenshot2](https://cloud.githubusercontent.com/assets/16081788/18204236/519bd182-7124-11e6-88f8-20d58f3e3bce.PNG)

**Comment by gugoan** [comment]
The situation occurred in the online version or the version of the repository?

**Comment by PRIHLOP** [comment]
The situation occured in the version of the repository(first screenshot), second screenshot from my repository with fix.

**Comment by PRIHLOP** [comment]
Thanks for responds.
