### ISSUE TITLE
404 error after instalation

### ISSUE THREAD

**Issue by ddr400** [gugoan/economizzer#90]
Hello,

I done a fresh instalation of the aplication and when i run it in the apache 2.4 i obtain the 404 error window with the message: The requested URL /user/login was not found on this server.

What could be missing in my Apache server?
First i was try to work with virtual hosts but after this issue, i'm trying to run the site as a default website of Apache.

Thanks!

**Comment by gugoan** [comment]
I just did a fresh install on windows 7 and not given error.
Try this:
```
git clone https://github.com/gugoan/economizzer.git
cd economizzer
composer install
```

Can be any configuration of your Apache. The REWRITE_MOD is enabled?

**Comment by ddr400** [comment]
Hello,
Thanks for your feedback.
I solve the issue putting the EnablePrettyUrl = false.
