### ISSUE TITLE
Error 404 - editing expense record

### ISSUE THREAD

**Issue by ddr400** [gugoan/economizzer#93]
Hello,
When i try to edit some expense record, the application return the following error:

![error](https://cloud.githubusercontent.com/assets/23192480/20060759/9a587160-a4f4-11e6-85ac-780a3de04d7b.png)

What could be the cause?

**Comment by ddr400** [comment]
Someone could help me?

**Comment by PRIHLOP** [comment]
Please attach logs files for web server and php. It help to resolve problem.

**Comment by ddr400** [comment]
Hello,
Where could i find that log's?
This is what i could see in the app.log file inside /runtime/logs folder:
![sem titulo](https://cloud.githubusercontent.com/assets/23192480/20141009/45b286c6-a686-11e6-8d4e-5a17013b61df.png)

**Comment by gugoan** [comment]
@ddr400 , Try this:
Replace the content of the "rowOptions" param in your `cashbook / index` file with the content below and delete your `.htaccess` file

```
'rowOptions'   => function ($model, $index, $widget, $grid) {
                return [
                    'id' => $model['id'], 
                    'onclick' => 'location.href="'
                        . Yii::$app->urlManager->createUrl('cashbook/update') 
                        . '&id="+(this.id);',
                    'style' => "cursor: pointer",
                ];
        },       
```
I will try a definitive solution and publish it later.

**Comment by ddr400** [comment]
Hello gugoan,
Thanks for the help!
Where is the cashbook / index file that you mentionned? I try to search in all folders and i didn't find it.

Best Regards,

**Comment by gugoan** [comment]
It is located at: `economizzer/views/cashbook/index.php`
Take a test and let me know

**Comment by ddr400** [comment]
Hello,
I made the test and it dosn't solve the issue.
Any other ideas?

**Comment by gugoan** [comment]
Does the error only happen when changing a record?
How is the URL when clicking the record you want to change?

**Comment by ddr400** [comment]
The issue happens when o try to change a record.
The url that appears in the bar is /r=cashbook/613

I got the same error when i try to edit an category (r=category/1013).

My instalation have the beautiful url= false.

**Comment by gugoan** [comment]
Along with the tips I passed above, comment on the "urlManager" parameter in "economizzer/config/web.php".
```
        // 'urlManager' => [
        //     'class' => 'yii\web\UrlManager',
        //     'showScriptName' => false,
        //     'enablePrettyUrl' => true,
        //     'rules' => array(
        //             '<controller:\w+>/<id:\d+>' => '<controller>/view',
        //             '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
        //             '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
        //             //'category/<id:\w+>' => 'category/view'
        //     ),
        // ],
```
The problem is happening because the URL's creation is considering that you are using `enablePrettyUrl`

**Comment by ddr400** [comment]
Hello.
I comment thaat urmManager code and that also don't solve the error.
My initial issue is that i couldn't run the app with the enable prettyirl = true.
If i start to change a lot of parameters in the configurations, i will have issues in a future update.
How can i solve my issues? in the demo of the project all the spects works fine but in my local server no.
Thanks!

**Comment by gugoan** [comment]
I'm trying to understand your environment where the application is installed to help you with the problem. The tests I asked for were just to understand that. We have to find out what the incompatibility is in your environment.

I have economizzer running normally on my pc (windows), my notebook (linux) and the cloud host (linux).

You're using linux, right? Is the "mod_rewrite" extension enabled? (It is required to use "prettyUrl").

**Comment by ddr400** [comment]
Hello,
Thanks for the feedback.
I'm using debian under my raspberry pi (jasen).
If i have the pretty url on, when access the page, i got the 404 error page:

![screenshot_1](https://cloud.githubusercontent.com/assets/23192480/20265322/5a4cb328-aa68-11e6-915f-dbcbb0a98d93.png)

I check and i have the module mod_rewrite active for apache.

I could give you the access to the server so you could check my environement if you need it.
Thanks!

**Comment by gugoan** [comment]
Right!
please take a look this post: [http://www.yiiframework.com/forum/index.php/topic/53295-url-manager-for-seo-friendly-url-404-error-code/](http://www.yiiframework.com/forum/index.php/topic/53295-url-manager-for-seo-friendly-url-404-error-code/)

Also see this post: [http://www.yiiframework.com/forum/index.php/topic/51470-pretty-urls-and-htaccess](http://www.yiiframework.com/forum/index.php/topic/51470-pretty-urls-and-htaccess)

**Comment by phprocks** [comment]
This is caused by some APACHE configuration. It is not system bug.

**Comment by ddr400** [comment]
Like PHPROCKS say, this is not a bug but an configuration issue of Apache.
Thanks guys. My issue is solved. Now it's time to make the translation to pt-PT and to publish it.

**Comment by gugoan** [comment]
I'm glad it worked 👍 
hug
