### ISSUE TITLE
currencycode exception on fresh install

### ISSUE THREAD

**Issue by firestalk** [gugoan/economizzer#96]
I have ubuntu 16.04, php7 and nginx. 
Following installation instructions, i have cloned repo, made composer magic and migrated db successfully.
PrettyUrls set to false
Then, when I trying to login with "joe" account, I see this error:

**Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: app\models\Profile::currencycode**

**Comment by gugoan** [comment]
@firestalk 
Try to use the sql file "economizzer.sql" in the project root. MIGRATIONS need to be fixed.

**Comment by kg-dexterity** [comment]
@firestalk 
You need to add below 2 columns in "profile" table manually in database.
currencycode -> varchar(20)
decimalseparator -> varchar(5)

**Comment by firestalk** [comment]
@kg-dexterity, thank you, it works now.

**Comment by gugoan** [comment]
You do not have to do it manually, the file I added is complete with all the tables and fields. (Only the MIGRATIONS are in trouble).
