### ISSUE TITLE
Mysql populated wrong for the first access - no user table

### ISSUE THREAD

**Issue by ndecaris** [gugoan/economizzer#98]
hi gustavo,

i can't access to economizzer with my self-hosted service.
i used default username : joe and the password associated, but i've got a pdo database exception in  return : "Table 'economizzer.user' doesn't exist"
i used mysql command to verify rights for userdatabase to access database : that's OK
further, i used "show tables;" command => no  user table, only those listed under :
+-----------------------+
| Tables_in_economizzer |
+-----------------------+
| cashbook              |
| category              |
| migration             |
+-----------------------+
i missed a mysql command to init the database ?

thanks in advance
Nicolas

**Comment by ndecaris** [comment]
hi again,

wrong syntax in sql file "migrations/m160320_200425_initial.sql", it begins with the table "profile", i can't find the mistake.
need help please !!!

thanks 
nicolas

**Comment by ndecaris** [comment]
i actually find the mistake in the sql file with quotation mark with the profile table foe currencycode and decimal separator.
other mistake value for the same table : currencycode and decimalseparator can't be null

=> it works with that.

* other bug : in the dashboard view : SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'economizzer.y.hexcolor_category' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

a question : how add a new currency (EURO) ?

thanks

**Comment by gugoan** [comment]
@ndecaris 
Try to use the sql file "economizzer.sql" in the project root. MIGRATIONS need to be fixed.

**Comment by ndecaris** [comment]
@gugoan 
no diff between economizzer.sql and m160320_200425_initial.sql files : go wrong !

"i actually find the mistake in the sql file with quotation mark with the profile table for currencycode and decimal separator.
other mistake value for the same table : currencycode and decimalseparator can't be null

=> it works with that."

what about the dashboard view database exception : "incompatible with sql_mode=only_full_group_by", is it a Mysql database configuration ?

thanks

**Comment by ndecaris** [comment]
i've modified in a fork the m160320_200425_initial.sql file

dashboard view is OK now : it was a global mysql parameter to change => SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

bug is closed for me

**Comment by gugoan** [comment]
I'll try to simulate this scenario. Thanks for the correction.
